### ISSUE TITLE
So much for this idea or not?

### ISSUE THREAD

**Issue by ghost** [Potato42/G2-3OTA#3]
So I have been trying to work on my spy game, and this 2/3 of the average game was left in the dust.
- I think it should be **half** the average, not 2/3, to make it simpler.
- How to download Jinja2 again?
- Why do I only have python2.7?

**Comment by benburrill** [comment]
Yeah, it kinda got abandoned.  I wanted to finish/fix the other one first but then I pretty much gave up on that too.  I'm actually considering creating a whole new KACPAW project since part of the problem with both of the old ones is lack of interest on my part.
- Half the average or 2/3 the average doesn't really make a difference in terms of code, but I suppose if I ever get around to finishing this I could make it easy to switch between them through a command line argument or something.
- `pip3 install jinja2` should do it once you have Python 3 + pip working
- Some platforms only have Python 2 installed by default.  It's easy to install Python 3 though.  You can go to https://python.org and download it, or use your favorite package manager for your platform.

BTW, do you use mac?  I seem to recall that you do from somewhere, and the only having Python 2 thing fits with that theory, but if I knew maybe I could offer less speculative and vague help for certain things.

**Comment by ghost** [comment]
Yes, I use mac.

What are you interested in? Perhaps we could come up with something that both of us would like.

**Comment by ghost** [comment]
By the way, I no longer wish to work on this project. I want freedom from KA's rules about not sending XMLHttpRequests and such. It would be nicer to make on my own website where I don't have to worry about people posting in a "Tips and Thanks", because I can just have it send a request to a server when they click.

If you want to continue this under kacpaw, go ahead. Perhaps get some other coding greats to help you out. But I think I can't continue this project. Perhaps I'll stop by every now and then and add a feature or two, but I can't be the _#_1 driving force on this.

**Comment by benburrill** [comment]
Yeah that's one of the reasons I've for the most part stopped working on kacpaw projects.  In retrospect I don't think kacpaw games were the greatest of ideas.  For the one kacpaw project I'm still (slowly) working on, I am only working on the game logic for now and trying to completely separate it from the IO and make it as easy as possible to use whatever you like as a server.  That way I can switch to Flask if I get frustrated but still want to work on the project.
